name: Continuous Integration

on: [pull_request]

jobs:
  notebooks-branch:
    name: Notebook Tests (branch)
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'
      - run: |
          pip install \
            seaborn \
            pytest-xdist \
            pytest \
            nbmake==0.2
      - run: |
          pytest --nbmake -n=auto docs
