name: Continuous Integration

on: [pull_request, push]

jobs:
  notebooks-branch:
    name: Notebook Tests (branch)
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'
      - run: |
          pip install \
            -r requirements.txt \
            -r dev_tools/conf/requirements-notebook-tests.txt \
            pytest-xdist \
            pytest \
            nbmake==0.1
      - run: | 
          pytest --nbmake -n=auto docs
